trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.dataviews_python.ini
  - name: analysisProject
    value: DataViews_Python

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          agentOS: Linux
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - script: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 2
        displayName: 'Alias Python 3.9'
        condition: eq(variables['Agent.OS'], 'Linux')

      - script: |
          echo Install test tools  
          python -m pip install pytest
          echo Install requirements
          python -m pip install -r requirements.txt
          echo Run tests
          python -m pytest --junit=junit/test-results.xml ./test.py
          echo Complete
        displayName: 'Install dependencies'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          useRequirementsTxt: true
